#!/bin/sh
# chkconfig: - 85 15
# description: memcached

CMD=/usr/local/memcached/bin/memcached
MEMORY=128
USER=root
HOST=192.168.0.100
PORT=11211
CONNECTION=256
PID=/tmp/memcached.pid

start() {
	echo -n $"Starting memcached: "  
	$CMD -d -m $MEMORY -u $USER -l $HOST -p $PORT -c $CONNECTION -P $PID
	echo
}

stop() {
	echo -n $"Shutting down memcached: "  
	kill `cat $PID`
	echo
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	*)
	echo $"Usage: $0 {start|stop|restart}"  
	exit 1
esac
exit 0